# Generated by Django 4.2.9 on 2024-04-20 19:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('preview', models.ImageField(upload_to='story_video_preview')),
                ('video_content', models.FileField(upload_to='story_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='story_viewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('avatar', models.ImageField(default='default_avatar.jpg', upload_to=main.models.avatar_directory_path)),
                ('background_avatar', models.ImageField(default='default_background_avatar.jpg', upload_to=main.models.bg_avatar_directory_path)),
                ('background_style', models.IntegerField(default=0)),
                ('amount_followers', models.IntegerField(default=0)),
                ('amount_following', models.IntegerField(default=0)),
                ('amount_article', models.IntegerField(default=0)),
                ('recommendations', models.TextField(default='', null=True)),
                ('verify', models.BooleanField(blank=True, default=False)),
                ('language', models.CharField(default='en', max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(blank=True)),
                ('online_status', models.BooleanField(default=False)),
                ('username_change_time', models.DateTimeField(blank=True)),
                ('followers', models.ManyToManyField(related_name='profile_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='profile_following', to=settings.AUTH_USER_MODEL)),
                ('notifications', models.ManyToManyField(related_name='profile_notification', to='main.profilenotification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('amount_likes', models.IntegerField(default=0)),
                ('amount_comments', models.IntegerField(default=0)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(to='main.articlecomment')),
                ('likes', models.ManyToManyField(related_name='articles_likes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='articles_likes', to='main.articletag')),
            ],
        ),
    ]
