# Generated by Django 4.2.9 on 2024-04-22 13:58

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.post_file_directory_path),
        ),
    ]
