# Generated by Django 4.2.9 on 2024-04-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postfile_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='poster',
        ),
    ]
