# Generated by Django 4.2.9 on 2024-04-26 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_profilefollow_profile_alter_profilefollow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilenotification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
