# Generated by Django 4.2.9 on 2024-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profilenotification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
