# Generated by Django 4.2.9 on 2024-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profilenotification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilenotification',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
