# Generated by Django 4.2.9 on 2024-04-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profilenotification_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenotification',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
    ]
