# Generated by Django 4.2.9 on 2024-05-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profilenotification_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='story',
            name='viewers',
        ),
    ]
