# Generated by Django 4.2.9 on 2024-05-03 11:24

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_story_preview_remove_story_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='video_content',
            field=models.FileField(upload_to=main.models.story_file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
