# Generated by Django 4.2.9 on 2024-05-03 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_alter_story_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='viewers',
            field=models.ManyToManyField(related_name='viewer_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
