# Generated by Django 5.0.6 on 2024-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_posttag_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_content_length',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
